import { CartProvider } from "@/contexts/CartContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="font-yekan ">
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
